version: '2'

volumes:
  solidity_compilers: {}
  vyper_compilers: {}
  brownie: {}
  cache: {}
  database: {}

x-common-volumes: &common-volumes
  - solidity_compilers:/root/.solcx
  - vyper_compilers:/root/.vvm
  - brownie:/root/.brownie
  - cache:/app/cache
  - database:/data

services:
  fastapi:
    build:
      context: ./
      dockerfile: ./src/services/fastapi/Dockerfile
    ports:
      - 80:8000
    restart: on-failure
    volumes:
      - database:/data
    environment:
      - DATABASE_URI

  api_cache_eth:
    build:
      context: ./
      dockerfile: ./src/services/api_cache/Dockerfile
    command: sh -c "brownie networks modify mainnet host=$ETH_PROVIDER; python by_network.py --network 1;"
    restart: on-failure
    volumes: *common-volumes
    environment:
      - ETH_PROVIDER
      - ETHERSCAN_TOKEN
      - DATABASE_URI
      - BROWNIE_NETWORK_ID=mainnet

  api_cache_ftm:
    build:
      context: ./
      dockerfile: ./src/services/api_cache/Dockerfile
    command: sh -c "brownie networks modify ftm-main host=$FTM_PROVIDER; python by_network.py --network 250;"
    restart: on-failure
    volumes: *common-volumes
    environment:
      - FTM_PROVIDER
      - FTMSCAN_TOKEN
      - DATABASE_URI
      - BROWNIE_NETWORK_ID=ftm-main

  api_cache_arb:
    build:
      context: ./
      dockerfile: ./src/services/api_cache/Dockerfile
    command: sh -c "brownie networks modify arbitrum-main host=$ARB_PROVIDER; python by_network.py --network 42161;"
    restart: on-failure
    volumes: *common-volumes
    environment:
      - ARB_PROVIDER
      - ARBISCAN_TOKEN
      - DATABASE_URI
      - BROWNIE_NETWORK_ID=arbitrum-main
