name: process-yearn-vision

on:
  schedule:
    - cron: "13 20 1 * *" # At 20:13 on the first of every month
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: generate random number
        id: random
        run: echo ::set-output name=value::$(echo $RANDOM)

      - name: checkout repository
        uses: actions/checkout@v3

      - name: install poetry
        run: pipx install poetry

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"

      - name: install python packages
        run: poetry install

      - name: execute python script
        run: poetry run python scripts/process_yearn_vision/main.py

      - name: check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)

      - name: checkout branch
        if: steps.git-check.outputs.modified == 'true'
        run: git checkout -b fix/process-yearn-vision-${{ steps.random.outputs.value }}

      - name: commit file
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -A
          git commit -m '[automated commit] fix: Update output.csv'
          git push -u origin fix/process-yearn-vision-${{ steps.random.outputs.value }}

      - name: create pull request
        uses: actions/github-script@v6
        if: steps.git-check.outputs.modified == 'true'
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[ref-${{ steps.random.outputs.value }}] Process Yearn Vision',
              owner,
              repo,
              head: 'fix/process-yearn-vision-${{ steps.random.outputs.value }}',
              base: '${{ github.ref_name }}',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n'),
              maintainer_can_modify: true,
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['automated pr']
            });
